#!/usr/bin/env python3
from secrets import SystemRandom as Sr
from argparse import ArgumentParser
import string as s


def generate_password(length=12, uppercase=True, lowercase=True, digits=True, symbols=False, key=''):
    characters = ''
    characters += key
    
    if uppercase:
        characters += s.ascii_uppercase
    if lowercase:
        characters += s.ascii_lowercase
    if digits:
        characters += s.digits
    if symbols:
        characters += s.punctuation
    
    if not characters:
        characters += s.ascii_letters + s.digits
    
    return ''.join(Sr().choices(characters, k=length))

def main():
    

    parser = ArgumentParser(
        description= "Generate a random alphanumeric password (uppercase and lowercase). Default length is 12 characters."
    )

    parser.add_argument(
        '-l', '--length',
        default=12,
        type=int,
        metavar="INT",
        help="Password length (default: 12)"
        )
    parser.add_argument(
        '-s', '--symbols',
        action='store_true',
        help="Enable punctuation symbols"
    )
    
    parser.add_argument(
        '-xd', '--exclude_digits',
        action='store_true',
        help="Disable digits"
    )
   
    only_group = parser.add_mutually_exclusive_group()
    only_group.add_argument(
        '-u', '-U', '--uppercase_only',
        action='store_true',
        help='Enable only uppercase'
        )
    only_group.add_argument(
        '-L', '--lowercase_only',
        action='store_true',
        help='Enable only lowercase'
        )
    
    args = parser.parse_args()
    
    upper = True
    lower = True
    digits = not args.exclude_digits

    
    if args.uppercase_only:
        upper = True
        lower = False
    elif args.lowercase_only:
        lower = True
        upper = False

    if args.exclude_digits:
        digits = False
        
    try:
        password = generate_password(
            length=args.length,
            uppercase=upper,
            lowercase=lower,
            digits=digits,
            symbols=args.symbols,
        )
        print(password)
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == '__main__':
    main()